### ISSUE TITLE
How to make gpt2 use the German model?

### ISSUE THREAD

**Issue by chwahnHTW** [gooofy/zbrain#1]
Hello,
I'm fairly new to Python & ML coming from a Java background. I hope this question is not completely misplaced .
I've successfully managed to download the official 345MM gpt2 Model and generate output with it, running on Google colab. 
Since I'm from Germany I want to use the German corpus to train a neural net, yet the provided readme does not make clear to me where the zbrain project runs and how to finetune the german gpt2 model provided by zbrain.

So far I've used Google Colab / Spyder to generate results using gtp2 like this : 

!pip install -q gpt-2-simple
import gpt_2_simple as gpt2
from datetime import datetime
from google.colab import files

gpt2.download_gpt2(model_name="345M")

gpt2.mount_gdrive()

file_name = "FinetuneCorpus.txt"
gpt2.copy_file_from_gdrive(file_name)

sess = gpt2.start_tf_sess()

gpt2.finetune(sess,
              dataset=file_name,
              model_name='345M',
              steps=1000,
              restore_from='fresh',
              run_name='run1',
              print_every=1,
              sample_every=20,
              save_every=50
              )
gpt2.generate(sess) 

Which parts of the model do I have to swap in order to make use of the zbrain model, instead of the one currently used?

**Comment by gooofy** [comment]
please check out 

https://github.com/gooofy/transformer-lm

for instructions on how to train and run the GPT-2 implementation used in zamia brain.

**Comment by hbajohr** [comment]
I wish there was a more detailed tutorial. Oh well.

**Comment by Donhomerj** [comment]
Can you share more information, on how you solved that issue? @han-baj 
Thanks!

**Comment by hafsahabib-educator** [comment]
@han-baj  @Donhomerj  did any of you solve the issue in more understandable way ?

**Comment by MichaelJanz** [comment]
What I did was, I copied the german model into the transformerlm/transformer-lm folder.
Then I was able to generate german text by using `gpt-2-gen run-root "Das ist ein Test"` as described here:[goofy/transformer-lm](https://github.com/gooofy/transformer-lm)

**Comment by hafsahabib-educator** [comment]
@MichaelJanz  thanks it worked. Now I am working on finetuning .

**Comment by tblock-zz** [comment]
Hello I tried to follow, but I had to do serveral things before it worked. So I give an update. Maybe it helps somebody.
Here is what I did:
GPT2 German On Windows Linux

virtualenv -p `which python3`  vgergpt2
source  vgpt2/bin/activate
pip install --upgrade pip
pip3 install tensorflow==1.14.0

git clone https://github.com/gooofy/transformer-lm
cd transformer-lm
pip3 install -r requirements.txt
python setup.py develop
wget  https://goofy.zamia.org/zamia-speech/brain/gpt2-german-345M-r20191119.tar.xz

#Then unzipped and untared the file. Now we need to create a directory in transformer-lm

sudo apt-get install xz-utils
unxz gpt2-german-345M-r20191119.tar.xz
tar -xvf gpt2-german-345M-r20191119.tar

mkdir transformer-lm/run-root 
chmod 755 transformer-lm/run-root

#Then move the files from the tar folder to run-root

mv de345-root/*  transformer-lm/run-root/
chmod 644 transformer-lm/run-root/*
rm -r de345-root/

Now you can run the test.

gpt-2-gen run-root "Das ist ein Test"
