### ISSUE TITLE
Error when Training 

### ISSUE THREAD

**Issue by chwahnHTW** [gooofy/zbrain#2]
I keep getting 
"bpe_model_trainer.cc(241) LOG(WARNING) No valid symbol found
trainer_interface.cc(508) LOG(INFO) Saving model: sp-model.model
Traceback (most recent call last):
  File "C:\Users\ZZZ\Anaconda3\Scripts\sp-train-script.py", line 11, in <module>
    load_entry_point('lm', 'console_scripts', 'sp-train')()
  File "c:\users\zzz\desktop\uni\usw\gpt2german\transformer-lm-master\transformer-lm-master\lm\data.py", line 62, in sp_train
    f'--character_coverage={args.character_coverage}',
RuntimeError: Internal: C:\projects\sentencepiece\src\trainer_interface.cc(499) [(trainer_spec_.vocab_size()) == (model_proto->pieces_size())]"

when trying to train the german gpt2 model. I've had a look at the transformer-lm documentation, but I cant figure out what the error is supposed to tell me.
I'd like to open the issuse on the transformer-lm repo, but the ability to open issues isn't given there. Please don't close the issue without answering it, I really want to use the model

**Comment by hafsahabib-educator** [comment]
@chwahnHTW  were you able to successfully finetune the pretrained german model ?
