### ISSUE TITLE
Using the German GPT-2 model to generate text

### ISSUE THREAD

**Issue by manueltonneau** [gooofy/zbrain#3]
Hi and thanks for this cool contribution! :) 

I downloaded the pre-trained GPT-2 models you trained and am hoping to use them to generate text. The issue is that the model files from the 345M version are in pt format which is unknown to me. Could you please provide some details on how to use these models to generate text in German? I was hoping to use gpt-2-simple with it. 
![image](https://user-images.githubusercontent.com/29440170/73187087-1cbb8900-4121-11ea-88b9-6589ca164581.png)

**Comment by gooofy** [comment]
you can use torch.load to load the .pt files. check out the file lm/inference.py for sample code on how to load the model for inference.
